name: EduPermissions
description: Sistema de Permissoes
main: net.eduard.permissions.EduPermissions
version: 1.0-SNAPSHOT
author: Eduard
authors: [Eduard]
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD

